kind: Service
apiVersion: v1
metadata:
  name: ipsec-vpn-home-layer2lb-svc
  namespace: hwdsl2-ipsec-vpn
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
    protocol.openelb.kubesphere.io/v1alpha1: layer2
    eip.openelb.kubesphere.io/v1alpha2: ipsec-vpn-home-eip
spec:
  selector:
    app: ipsec-vpn-home
  type: LoadBalancer
  ports:
    - name: isakmp
      port: 500
      targetPort: 500
      protocol: UDP
    - name: ipsec-msft
      port: 4500
      targetPort: 4500
      protocol: UDP
  externalTrafficPolicy: Cluster

