apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hwdsl2-ipsec-vpn-server-longhorn-pvc
  namespace: hwdsl2-ipsec-vpn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi
