kind: Service
apiVersion: v1
metadata:
  name: ipsec-vpn-home-layer2lb-svc
  namespace: hwdsl2-ipsec-vpn
  annotations:
spec:
  selector:
    app: ipsec-vpn-home
  type: LoadBalancer
  loadBalancerIP: 172.16.1.110
  ports:
    - name: isakmp
      port: 500
      targetPort: 500
      protocol: UDP
    - name: ipsec-msft
      port: 4500
      targetPort: 4500
      protocol: UDP
  externalTrafficPolicy: Cluster

